CONNECTION_TIMEOUT_IN_SECONDS = 3

NEW_USER_REWARD = 100

MINING_REWARD = 50

RAFT_ELECTION_TIMEOUT_LOWER_IN_MS = 20000

RAFT_ELECTION_TIMEOUT_UPPER_IN_MS = 30000

RAFT_LEADER_HEARTBEAT_INTERVAL_IN_MS = 5000
